// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDistributionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistributionRequest) Reset() {
	*x = GetDistributionRequest{}
	mi := &file_api_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistributionRequest) ProtoMessage() {}

func (x *GetDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistributionRequest.ProtoReflect.Descriptor instead.
func (*GetDistributionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetDistributionRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type GetDistributionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Raw           *Metrics               `protobuf:"bytes,5,opt,name=raw,proto3" json:"raw,omitempty"`
	Filtered      *Metrics               `protobuf:"bytes,6,opt,name=filtered,proto3" json:"filtered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDistributionResponse) Reset() {
	*x = GetDistributionResponse{}
	mi := &file_api_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistributionResponse) ProtoMessage() {}

func (x *GetDistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistributionResponse.ProtoReflect.Descriptor instead.
func (*GetDistributionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistributionResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *GetDistributionResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetDistributionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetDistributionResponse) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetDistributionResponse) GetRaw() *Metrics {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *GetDistributionResponse) GetFiltered() *Metrics {
	if x != nil {
		return x.Filtered
	}
	return nil
}

type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HolderCount   int64                  `protobuf:"varint,1,opt,name=holder_count,json=holderCount,proto3" json:"holder_count,omitempty"`
	Gini          float64                `protobuf:"fixed64,2,opt,name=gini,proto3" json:"gini,omitempty"`
	Nakamoto      int64                  `protobuf:"varint,3,opt,name=nakamoto,proto3" json:"nakamoto,omitempty"`
	Hhi           float64                `protobuf:"fixed64,4,opt,name=hhi,proto3" json:"hhi,omitempty"`
	Buckets       []*Bucket              `protobuf:"bytes,5,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_api_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *Metrics) GetHolderCount() int64 {
	if x != nil {
		return x.HolderCount
	}
	return 0
}

func (x *Metrics) GetGini() float64 {
	if x != nil {
		return x.Gini
	}
	return 0
}

func (x *Metrics) GetNakamoto() int64 {
	if x != nil {
		return x.Nakamoto
	}
	return 0
}

func (x *Metrics) GetHhi() float64 {
	if x != nil {
		return x.Hhi
	}
	return 0
}

func (x *Metrics) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	MinShare      string                 `protobuf:"bytes,2,opt,name=min_share,json=minShare,proto3" json:"min_share,omitempty"`
	HolderCount   int64                  `protobuf:"varint,3,opt,name=holder_count,json=holderCount,proto3" json:"holder_count,omitempty"`
	TotalBalance  string                 `protobuf:"bytes,4,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_api_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_api_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *Bucket) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Bucket) GetMinShare() string {
	if x != nil {
		return x.MinShare
	}
	return ""
}

func (x *Bucket) GetHolderCount() int64 {
	if x != nil {
		return x.HolderCount
	}
	return 0
}

func (x *Bucket) GetTotalBalance() string {
	if x != nil {
		return x.TotalBalance
	}
	return ""
}

var File_api_proto_analytics_proto protoreflect.FileDescriptor

const file_api_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/analytics.proto\x12\fanalytics.v1\"9\n" +
	"\x16GetDistributionRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"\xe5\x01\n" +
	"\x17GetDistributionResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x03R\vblockNumber\x12'\n" +
	"\x03raw\x18\x05 \x01(\v2\x15.analytics.v1.MetricsR\x03raw\x121\n" +
	"\bfiltered\x18\x06 \x01(\v2\x15.analytics.v1.MetricsR\bfiltered\"\x9e\x01\n" +
	"\aMetrics\x12!\n" +
	"\fholder_count\x18\x01 \x01(\x03R\vholderCount\x12\x12\n" +
	"\x04gini\x18\x02 \x01(\x01R\x04gini\x12\x1a\n" +
	"\bnakamoto\x18\x03 \x01(\x03R\bnakamoto\x12\x10\n" +
	"\x03hhi\x18\x04 \x01(\x01R\x03hhi\x12.\n" +
	"\abuckets\x18\x05 \x03(\v2\x14.analytics.v1.BucketR\abuckets\"\x83\x01\n" +
	"\x06Bucket\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\tmin_share\x18\x02 \x01(\tR\bminShare\x12!\n" +
	"\fholder_count\x18\x03 \x01(\x03R\vholderCount\x12#\n" +
	"\rtotal_balance\x18\x04 \x01(\tR\ftotalBalance2r\n" +
	"\x10AnalyticsService\x12^\n" +
	"\x0fGetDistribution\x12$.analytics.v1.GetDistributionRequest\x1a%.analytics.v1.GetDistributionResponseBAZ?github.com/gfournierPro/erc20-analyzer/internal/analytics/pb;pbb\x06proto3"

var (
	file_api_proto_analytics_proto_rawDescOnce sync.Once
	file_api_proto_analytics_proto_rawDescData []byte
)

func file_api_proto_analytics_proto_rawDescGZIP() []byte {
	file_api_proto_analytics_proto_rawDescOnce.Do(func() {
		file_api_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_analytics_proto_rawDesc), len(file_api_proto_analytics_proto_rawDesc)))
	})
	return file_api_proto_analytics_proto_rawDescData
}

var file_api_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_analytics_proto_goTypes = []any{
	(*GetDistributionRequest)(nil),  // 0: analytics.v1.GetDistributionRequest
	(*GetDistributionResponse)(nil), // 1: analytics.v1.GetDistributionResponse
	(*Metrics)(nil),                 // 2: analytics.v1.Metrics
	(*Bucket)(nil),                  // 3: analytics.v1.Bucket
}
var file_api_proto_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.v1.GetDistributionResponse.raw:type_name -> analytics.v1.Metrics
	2, // 1: analytics.v1.GetDistributionResponse.filtered:type_name -> analytics.v1.Metrics
	3, // 2: analytics.v1.Metrics.buckets:type_name -> analytics.v1.Bucket
	0, // 3: analytics.v1.AnalyticsService.GetDistribution:input_type -> analytics.v1.GetDistributionRequest
	1, // 4: analytics.v1.AnalyticsService.GetDistribution:output_type -> analytics.v1.GetDistributionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_analytics_proto_init() }
func file_api_proto_analytics_proto_init() {
	if File_api_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_analytics_proto_rawDesc), len(file_api_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_analytics_proto_goTypes,
		DependencyIndexes: file_api_proto_analytics_proto_depIdxs,
		MessageInfos:      file_api_proto_analytics_proto_msgTypes,
	}.Build()
	File_api_proto_analytics_proto = out.File
	file_api_proto_analytics_proto_goTypes = nil
	file_api_proto_analytics_proto_depIdxs = nil
}
